language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: NappPZueKN/sLgsdCBcGhEgLM9MvapptHH+bmSi7Afg192Vt/4H6aDdlJxl1P7YLw6F/gVb7qOzT69QiN34rwGrT0bRffkN6/WhJ2YaWy1XTIXXCSUn+tOdm5noWIL2s5KMbS9NQBBIPZrHJ0vGMWxsWYiwFgqIo5xjsTpbDCnJ50VVZsIfPWeBaD2nIYV2GJsEPBTZiTnS7a6iIsVTGog5lG6Xw5qaeJm58v93uRQlRiSNn7yiDVoFfUVS2PZ4ItB78wHssUgHvBiq4b+C0LEYFqwikR5ZAjnr+AnhxfZULAOj19RdpHsXmztjnaFuQjdNoSAKgnmd0xVy5R05lEB2RNAq293s9kJtjuKoVFhC2gpap3096th+p1pqwYfX28NCBoKzRovsbcu49w3K2pKexKG3NLt9hzy3u+RkwJ3hw8hAkN28ZajrJ0ubCWQfvPPQCsAJp9aI7v9Lvf1Fk6ofl25GbppVivmtgmecvRc8PGeeiZBRmIxQ+wmmgRQj9AAXI/DaK5g48biyq2JAUP55+7pnweOY81P3w10UnrGlYB8TPoPb8MhFbURorsy0ygIy9bFHlLUl8HX4Thiphe6InVt88mbAoXe4n75CFBEl5B2Katg9mFb2cA0Y5Uk6kT8VBnfqV6EAmYsUdaaVrsus96OuwYHpvVp8tqgVEMnw=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: gBnic4Dg287b4bo1x8FpB1nuaI2QHS3zxe4jIpDC7fhJsKORpUTYhNA1qJYtNEV5g954O8HAUy8YPE5OVvNO7gV2eq89V1kRllSqfVKH7aWnlUNNI6ab3IS4PxLtNIbp7KZE98bRCY+GIgG8gd9gaQ+XvmOqqYPjYGn7nbqV5IyvNvXOrYX3CWxnQ6Tg+Qw00ugwPhLlaktJpngRWZ+oKo5dIHtbLAJxe3dtfK39I3DfDNm4KCBzfpFv/UYTPAN9F0tVX5xX9GpxMFAQhRbtjvtAggfkQte0ZJwZCcU8MjkSqPhWVK5Zl2rbe2Uj+yBV/w8n/Yq5z+i3kKSABifDor0LV54u2Q1ua3Ilbq1M6VvnsHDLqG34Rdd2hSt6192sKb46AkwvonadmL1MjkFvJX0MaTjDagmL3t2Vh3QA5XFYV4LaP3Dv90kRWi4VwTgLtds2N4jKP8biRlko32bKdJNxY2asWGH+etcx9+WKlmyDli1VIYglIQf9kLazAnKc78olehczG+WgbFI0VBNMLoDAEmcRTfvGPDMnxOIe5C50VXN4roxDzGco0kc+fXhb2o/GZkOrAE063BDGnuVl20iMqkPTAEaHhMjk10kWOQ/mtGGP8nP8/5ethsX7+rShe2Mo/SI3IR3Je1+z/PRn3mSrVaO0Wa2L7fG/aLdvV5U=
sudo: false
